version: '3.8'
services:
  app:
    build: .
    environment:
     - Salt=salt
     - Secret="secret
     - Port=:8080
     - EML_EMAIL =yelllowflash@mail.ru
     - EML_PASSWORD=fKSfjTpRF7ewrATCzSkH
     - DB_HOST=db
     - DB_PORT=5432
     - DB_USER=postgres
     - DB_PASSWORD=123456789sq
     - DB_DBNAME=postgres
     - DB_SSLMODE=disable

    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789sq
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"